### ISSUE TITLE
drag & drop과 delete

### ISSUE THREAD

**Issue by YJH2848** [soogung/simblue-client#90]
### ✨ Describe

기록들을 드래그앤 드랍 및 삭제

### ✅ Tasks

- [x] 기록 드래그 구현
- [x] 기록 수직드랍 구현
- [x] 기록 수평드랍 구현
- [ ] 신청 종료 구현

### 🙋🏻 More

금방 끝내겠습니다. 죄송합니다 금방 못 끝낼 거 같습니다
